apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    selector:
      matchLabels:
        app: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mysql
        annotations:
          vault.hashicorp.com/agent-inject: "true"
          vault.hashicorp.com/agent-inject-status: "update"
          vault.hashicorp.com/agent-inject-secret-sendmail: "secret/sendmail-api"
          vault.hashicorp.com/agent-inject-template-sendmail: |
              {{- with secret "secret/sendmail-api" -}}
              # smtp relay api key
              APIKEY={{ .Data.data.APIKEY }}
              {{- end }}
          vault.hashicorp.com/role: "internal-app"

      spec:
        serviceAccountName: internal-app
        containers:
          - image: mysql:5.6
            name: mysql
#            env:
#              # Use secret in real usage
#              - name: MYSQL_ROOT_PASSWORD
#                value: admin
            ports:
              - containerPort: 3306
                name: mysql

            volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
        volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim



