apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    selector:
      matchLabels:
        app: mysql
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: mysql
        annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-inject-status: "update"
            vault.hashicorp.com/agent-inject-secret-database: "secret/database"
            vault.hashicorp.com/role: "mysql"
            vault.hashicorp.com/auth-path: "/auth/kubernetes"
            vault.hashicorp.com/agent-inject-template-database: |
              {{- with secret "secret/database" -}}
              export MYSQL_ROOT_PASSWORD={{ .Data.data.password }}
              {{- end }}

      spec:
        serviceAccountName: mysql
        containers:
          - image: mysql:5.6
            name: mysql
            command: ["/entrypoint.sh"]
            args:
              [ 'sh', '-c', '. /vault/secrets/database && mysqld']
#            env:
#              # Use secret in real usage
#              - name: MYSQL_ROOT_PASSWORD
#                value: admin
            ports:
              - containerPort: 3306
                name: mysql
            volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
        volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim
